import { ProjectItem, TestimonialItem, ServiceTier } from './types';

export const PROJECTS: ProjectItem[] = [
  {
    id: 'p1',
    title: 'GraminBazaar – Rural Direct E-Commerce Platform',
    category: 'Fullstack & PWA',
    description: 'Ultra-lite web application allowing farmers and village artisans to sell produce directly to buyers with voice search in local languages and offline sync.',
    region: 'in_rural',
    tags: ['Next.js', 'PWA', 'Voice AI', 'UPI Integration', 'Hindi/Marathi'],
    metrics: '⚡ 40,000+ Rural Farmers Onboarded | 3.2x Revenue Growth',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    liveUrl: 'https://example.com/graminbazaar',
  },
  {
    id: 'p2',
    title: 'FinPulse AI – High-Frequency Trading & Wealth Dashboard',
    category: 'Fintech & Real-time AI',
    description: 'Institutional trading dashboard with sub-millisecond WebSocket data streams, predictive market sentiment AI models, and algorithmic execution.',
    region: 'in_metro',
    tags: ['React 18', 'TypeScript', 'Tailwind', 'Python Fast API', 'WebSockets'],
    metrics: '🚀 $120M Monthly Volume Processed | 99.999% Uptime',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=800&q=80',
    liveUrl: 'https://example.com/finpulse',
  },
  {
    id: 'p3',
    title: 'OmniCloud Enterprise AI Workflow Automation',
    category: 'Enterprise SaaS',
    description: 'Multi-tenant enterprise agentic AI orchestrator integrating legacy ERP databases with automated LLM reasoning and SOC2 compliant audit trails.',
    region: 'us_corp',
    tags: ['Next.js App Router', 'LangChain', 'PostgreSQL', 'Stripe', 'OAuth 2.0'],
    metrics: '💼 Saved 4,500+ Hours Monthly for Fortune 500 Enterprise',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80',
    liveUrl: 'https://example.com/omnicloud',
  },
  {
    id: 'p4',
    title: 'KuroDigital – European Sustainable Design System',
    category: 'Design System & Accessibility',
    description: 'WCAG AAA accessible UI kit with dynamic dark/light themes, zero-cls layout engine, and zero-carbon footprint optimization.',
    region: 'eu_minimal',
    tags: ['WCAG AAA', 'Tailwind CSS', 'Framer Motion', 'Performance Optimization'],
    metrics: '🌿 100/100 Google Lighthouse Score | 0.08g CO2 per Pageview',
    image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80',
    liveUrl: 'https://example.com/kurodigital',
  },
  {
    id: 'p5',
    title: 'NeoTokyo AI Smart City Logistics Portal',
    category: 'Smart Mobility & IoT',
    description: 'Real-time Autonomous Delivery fleet routing console featuring interactive 3D WebGL maps, battery optimization telemetry, and Japanese speech alerts.',
    region: 'apac_startup',
    tags: ['Three.js', 'WebGL', 'Next.js', 'Web Speech API', 'IoT Stream'],
    metrics: '🎌 Active in 3 Major APAC Hubs | 28% Delivery Efficiency Boost',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=80',
    liveUrl: 'https://example.com/neotokyo',
  },
];

export const TESTIMONIALS: TestimonialItem[] = [
  {
    id: 't1',
    name: 'Balasaheb Patil',
    role: 'Co-founder & President',
    company: 'Sangamner Agro Farmers Cooperative',
    location: 'Sangamner, Maharashtra',
    region: 'in_rural',
    avatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=300&q=80',
    quote: 'Dnyaneshwar translated our village business needs into a mobile app that even elderly farmers can use effortlessly with voice input in Marathi. Truly our local champion!',
    rating: 5,
  },
  {
    id: 't2',
    name: 'Ananya Sharma',
    role: 'VP of Engineering',
    company: 'ZettaScale Technologies',
    location: 'Bengaluru, Karnataka',
    region: 'in_metro',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    quote: 'WorldFolio X demonstrates astounding engineering speed. Dnyaneshwar rebuilt our frontend core in Next.js 14, cutting payload by 65% and delivering buttery smooth 60fps UI.',
    rating: 5,
  },
  {
    id: 't3',
    name: 'Marcus Vance',
    role: 'Chief Technology Officer',
    company: 'Apex Cloud Ventures',
    location: 'San Francisco, CA',
    region: 'us_corp',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    quote: 'WorldFolio X blew our board members away. The AI personalization and immediate localization convinced us instantly to award our entire microservice overhaul project to Dnyaneshwar.',
    rating: 5,
  },
  {
    id: 't4',
    name: 'Dr. Elena Rostova',
    role: 'Head of Product',
    company: 'Zürich CleanTech Systems',
    location: 'Zurich, Switzerland',
    region: 'eu_minimal',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    quote: 'The level of craftsmanship, accessibility attention, clean code architecture, and multi-language fluency makes working with Dnyaneshwar an absolute joy.',
    rating: 5,
  },
  {
    id: 't5',
    name: 'Kenji Sato',
    role: 'Founder & CEO',
    company: 'FutureTokyo AI Labs',
    location: 'Tokyo, Japan',
    region: 'apac_startup',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    quote: 'From rural origins to world-class AI mastery! WorldFolio X showcases unmatched adaptability and real-time execution.',
    rating: 5,
  },
];

export const SERVICE_TIERS: ServiceTier[] = [
  {
    id: 'tier_local',
    title: 'स्थानिक टियर (Gramin & Taluka)',
    tagline: 'गांव आणि तालुका व्यापारी यांच्यासाठी',
    inrPrice: 3999,
    usdPrice: 49,
    features: [
      'Hyper-Fast Next.js 14 Web Application',
      'Mobile-First & PWA Offline Support',
      'Multi-Language UI (English, Hindi, Marathi)',
      'Instant WhatsApp & Calling Integration',
      '1 Year Free Hosting Setup & Maintenance',
    ],
  },
  {
    id: 'tier_national',
    title: 'नॅशनल टियर (Indian Startups)',
    tagline: 'भारतीय स्टार्टअप्स आणि ग्रोइंग ब्रँड्ससाठी',
    inrPrice: 14999,
    usdPrice: 199,
    popular: true,
    features: [
      'Full Geo-Adaptive Persona & AI Localization',
      'Custom Real-Time AI Chatbot & Voice Navigation',
      'Stripe & UPI Payment Gateway Integration',
      'Prisma DB Setup & Admin Dashboard',
      '100/100 Lighthouse Performance & AAA Accessibility',
      '24/7 Priority Support & Direct Tech Lead Access',
    ],
  },
  {
    id: 'tier_international',
    title: 'इंटरनॅशनल टियर (Global Clients)',
    tagline: 'ग्लोबल क्लायंट्स आणि इंटरनॅशनल SaaS साठी',
    inrPrice: 49999,
    usdPrice: 49,
    features: [
      'Custom LLM & RAG Pipeline Orchestration ($49/hr rate)',
      'High-Frequency Microservice Engineering',
      'Blockchain Credential Badges & Security Audits',
      'Custom On-Premise / Hybrid Cloud Deployment',
      'Dedicated SLA & Strategic Tech Advisory',
    ],
  },
];

export const TIMELINE_STORY = [
  {
    year: '2021',
    title: 'The Village Ignition 🌾',
    subtitle: 'Sangamner, Maharashtra',
    description: 'Started coding on a second-hand laptop with patchy 3G connectivity in a small village. Built custom billing software and inventory trackers for local agro shopkeepers and artisans.',
  },
  {
    year: '2023',
    title: 'Crossing Boundaries 🚀',
    subtitle: 'Metro Tech Ecosystem',
    description: 'Architected high-concurrency microservices, state management engines, and real-time WebSockets. Scaled applications to millions of daily requests for tech unicorns in Bengaluru and Mumbai.',
  },
  {
    year: '2024',
    title: 'Global AI Expansion 🌍',
    subtitle: 'Silicon Valley & European Clients',
    description: 'Pioneered hyper-adaptive web systems, edge-computed AI translations, multi-modal interfaces, and voice-assisted digital experiences for global clients.',
  },
  {
    year: '2026',
    title: 'WorldFolio X Epoch ⚡',
    subtitle: 'Global Reach from Local Roots',
    description: 'Created WorldFolio X – an autonomous, hyper-adaptive portfolio built in under 90 minutes that bridges village simplicity with corporate global power.',
  },
];
