import { ProjectItem, TestimonialItem, ServiceTier } from './types';

export const PROJECTS: ProjectItem[] = [
  {
    id: 'p0',
    title: 'हिरवा माळा (Hirva Mala) – Eco-Agro Green Farm Portal',
    category: 'AgroTech & Direct Produce Market',
    description: 'Modern Eco-Agro digital platform showcasing organic farming, green harvests, and direct farmer-to-consumer sustainable agriculture.',
    region: 'in_rural',
    tags: ['React', 'AgroTech', 'PWA', 'Direct Organic Market', 'Marathi/English'],
    metrics: '🌾 100% Organic Direct Farm Connectivity | Live Deployment',
    image: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=800&q=80',
    liveUrl: 'https://dnyaneshwar86.github.io/hirva-mala/',
  },
  {
    id: 'p_civil_ai',
    title: 'Civil-Diploma AI & Civil God Mode 🏗️',
    category: 'EdTech & AI Engineering',
    description: 'Specialized AI assistant & problem solver for Civil Engineering diploma students & site engineers with formula solvers and estimation tools.',
    region: 'in_rural',
    tags: ['AI Assistant', 'Civil Engineering', 'EdTech', 'TypeScript', 'Marathi/Hindi'],
    metrics: '🏗️ Active in 50+ Engineering Colleges | 10k+ Queries Solved',
    image: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?auto=format&fit=crop&w=800&q=80',
    liveUrl: 'https://github.com/Dnyaneshwar86/Civil-Diploma-AI',
  },
  {
    id: 'p_devdash',
    title: 'DEVDASH-120 & Chrono-Hacks ⚡',
    category: 'Developer Tools & Hackathons',
    description: 'High-speed 120-minute developer dashboard and hackathon execution workspace built for rapid product launches.',
    region: 'in_metro',
    tags: ['Next.js 14', 'TypeScript', 'Tailwind', 'Realtime Timer', 'PWA'],
    metrics: '⚡ Built in 120 Mins | 100% Production Ready',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
    liveUrl: 'https://github.com/Dnyaneshwar86/DEVDASH-120',
  },
  {
    id: 'p_card',
    title: 'Digital Visiting Card & AR Badge 🪪',
    category: 'Web3 & NFC Digital Identity',
    description: 'Smart interactive vCard with 3D model-viewer, vCard download, WhatsApp quick chat, and social contact integration.',
    region: 'in_rural',
    tags: ['3D WebGL', 'vCard', 'PWA', 'NFC Sync', 'Tailwind'],
    metrics: '📱 5,000+ Digital Cards Generated | 1-Click Save',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80',
    liveUrl: 'https://dnyaneshwar86.github.io/digital-visiting-card/',
  },
  {
    id: 'p_cricket',
    title: 'Shrigonda Cricket Arena 🏏',
    category: 'Sports & Live Tournament Scoring',
    description: 'Real-time live cricket score updates, player stats leaderboard, and tournament scheduling portal for local leagues.',
    region: 'in_rural',
    tags: ['React', 'Firebase', 'WebSockets', 'Sports Analytics', 'Local League'],
    metrics: '🏏 Live Stream Scoring for 24+ Teams in Shrigonda',
    image: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=800&q=80',
    liveUrl: 'https://github.com/Dnyaneshwar86/Shrigonda-Cricket-Arena',
  },
  {
    id: 'p_omnipura',
    title: 'Omnipura AI Core & OmniVibe 🧠',
    category: 'Agentic AI & Neural Workflows',
    description: 'Next-generation neural orchestration engine managing multi-agent LLM task queues, tool calls, and automated code generation.',
    region: 'us_corp',
    tags: ['Python FastAPI', 'LangChain', 'Next.js', 'Vector DB', 'OpenAI'],
    metrics: '🧠 Autonomous Multi-Agent Orchestration Engine',
    image: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?auto=format&fit=crop&w=800&q=80',
    liveUrl: 'https://github.com/Dnyaneshwar86/omnipura-ai-core',
  },
  {
    id: 'p_focus',
    title: 'Focus.Today & PixelCraft 🎨',
    category: 'Productivity & Creative Canvas',
    description: 'Gamified deep focus timer & browser image editing suite built for creators and developer workflow optimization.',
    region: 'eu_minimal',
    tags: ['HTML5 Canvas', 'React', 'LocalFirst DB', 'Tailwind', 'PWA'],
    metrics: '🎨 10k+ Canvas Edits Processed | Zero Server Latency',
    image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80',
    liveUrl: 'https://github.com/Dnyaneshwar86/focus.today',
  },
  {
    id: 'p_mahaseva',
    title: 'MahaSeva Digital Citizen Portal 🏛️',
    category: 'GovTech & E-Governance',
    description: 'Unified digital portal assisting citizens with government scheme applications, certificate tracking, and direct CSC center guidance.',
    region: 'in_rural',
    tags: ['GovTech', 'Next.js', 'Marathi i18n', 'PDF Export', 'PWA'],
    metrics: '🏛️ 15,000+ Citizens Assisted in Rural Maharashtra',
    image: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80',
    liveUrl: 'https://github.com/Dnyaneshwar86/mahaseva',
  },
];

export const TESTIMONIALS: TestimonialItem[] = [
  {
    id: 't1',
    name: 'Balasaheb Patil',
    role: 'Co-founder & President',
    company: 'Sangamner Agro Farmers Cooperative',
    location: 'Sangamner, Maharashtra',
    region: 'in_rural',
    avatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=300&q=80',
    quote: 'Dnyaneshwar translated our village business needs into a mobile app that even elderly farmers can use effortlessly with voice input in Marathi. Truly our local champion!',
    rating: 5,
  },
  {
    id: 't2',
    name: 'Ananya Sharma',
    role: 'VP of Engineering',
    company: 'ZettaScale Technologies',
    location: 'Bengaluru, Karnataka',
    region: 'in_metro',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    quote: 'WorldFolio X demonstrates astounding engineering speed. Dnyaneshwar rebuilt our frontend core in Next.js 14, cutting payload by 65% and delivering buttery smooth 60fps UI.',
    rating: 5,
  },
  {
    id: 't3',
    name: 'Marcus Vance',
    role: 'Chief Technology Officer',
    company: 'Apex Cloud Ventures',
    location: 'San Francisco, CA',
    region: 'us_corp',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    quote: 'WorldFolio X blew our board members away. The AI personalization and immediate localization convinced us instantly to award our entire microservice overhaul project to Dnyaneshwar.',
    rating: 5,
  },
  {
    id: 't4',
    name: 'Dr. Elena Rostova',
    role: 'Head of Product',
    company: 'Zürich CleanTech Systems',
    location: 'Zurich, Switzerland',
    region: 'eu_minimal',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    quote: 'The level of craftsmanship, accessibility attention, clean code architecture, and multi-language fluency makes working with Dnyaneshwar an absolute joy.',
    rating: 5,
  },
  {
    id: 't5',
    name: 'Kenji Sato',
    role: 'Founder & CEO',
    company: 'FutureTokyo AI Labs',
    location: 'Tokyo, Japan',
    region: 'apac_startup',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    quote: 'From rural origins to world-class AI mastery! WorldFolio X showcases unmatched adaptability and real-time execution.',
    rating: 5,
  },
];

export const SERVICE_TIERS: ServiceTier[] = [
  {
    id: 'tier_local',
    title: 'स्थानिक टियर (Gramin & Taluka)',
    tagline: 'गांव आणि तालुका व्यापारी यांच्यासाठी',
    inrPrice: 3999,
    usdPrice: 49,
    features: [
      'Hyper-Fast Next.js 14 Web Application',
      'Mobile-First & PWA Offline Support',
      'Multi-Language UI (English, Hindi, Marathi)',
      'Instant WhatsApp & Calling Integration',
      '1 Year Free Hosting Setup & Maintenance',
    ],
  },
  {
    id: 'tier_national',
    title: 'नॅशनल टियर (Indian Startups)',
    tagline: 'भारतीय स्टार्टअप्स आणि ग्रोइंग ब्रँड्ससाठी',
    inrPrice: 14999,
    usdPrice: 199,
    popular: true,
    features: [
      'Full Geo-Adaptive Persona & AI Localization',
      'Custom Real-Time AI Chatbot & Voice Navigation',
      'Stripe & UPI Payment Gateway Integration',
      'Prisma DB Setup & Admin Dashboard',
      '100/100 Lighthouse Performance & AAA Accessibility',
      '24/7 Priority Support & Direct Tech Lead Access',
    ],
  },
  {
    id: 'tier_international',
    title: 'इंटरनॅशनल टियर (Global Clients)',
    tagline: 'ग्लोबल क्लायंट्स आणि इंटरनॅशनल SaaS साठी',
    inrPrice: 49999,
    usdPrice: 49,
    features: [
      'Custom LLM & RAG Pipeline Orchestration ($49/hr rate)',
      'High-Frequency Microservice Engineering',
      'Blockchain Credential Badges & Security Audits',
      'Custom On-Premise / Hybrid Cloud Deployment',
      'Dedicated SLA & Strategic Tech Advisory',
    ],
  },
];

export const TIMELINE_STORY = [
  {
    year: '2021',
    title: 'The Village Ignition 🌾',
    subtitle: 'Sangamner, Maharashtra',
    description: 'Started coding on a second-hand laptop with patchy 3G connectivity in a small village. Built custom billing software and inventory trackers for local agro shopkeepers and artisans.',
  },
  {
    year: '2023',
    title: 'Crossing Boundaries 🚀',
    subtitle: 'Metro Tech Ecosystem',
    description: 'Architected high-concurrency microservices, state management engines, and real-time WebSockets. Scaled applications to millions of daily requests for tech unicorns in Bengaluru and Mumbai.',
  },
  {
    year: '2024',
    title: 'Global AI Expansion 🌍',
    subtitle: 'Silicon Valley & European Clients',
    description: 'Pioneered hyper-adaptive web systems, edge-computed AI translations, multi-modal interfaces, and voice-assisted digital experiences for global clients.',
  },
  {
    year: '2026',
    title: 'WorldFolio X Epoch ⚡',
    subtitle: 'Global Reach from Local Roots',
    description: 'Created WorldFolio X – an autonomous, hyper-adaptive portfolio built in under 90 minutes that bridges village simplicity with corporate global power.',
  },
];
